//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-3273 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.05.12 at 11:47:00 AM PDT 
//


package com.sun.japex.testsuite;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sun.japex.testsuite package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sun.japex.testsuite
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DriverGroupType }
     * 
     */
    public DriverGroupType createDriverGroupType() {
        return new DriverGroupType();
    }

    /**
     * Create an instance of {@link ParamType }
     * 
     */
    public ParamType createParamType() {
        return new ParamType();
    }

    /**
     * Create an instance of {@link TestCaseGroupType }
     * 
     */
    public TestCaseGroupType createTestCaseGroupType() {
        return new TestCaseGroupType();
    }

    /**
     * Create an instance of {@link DriverType }
     * 
     */
    public DriverType createDriverType() {
        return new DriverType();
    }

    /**
     * Create an instance of {@link TestSuiteElement }
     * 
     */
    public TestSuiteElement createTestSuiteElement() {
        return new TestSuiteElement();
    }

    /**
     * Create an instance of {@link ParamOrParamGroupType }
     * 
     */
    public ParamOrParamGroupType createParamOrParamGroupType() {
        return new ParamOrParamGroupType();
    }

    /**
     * Create an instance of {@link TestCaseType }
     * 
     */
    public TestCaseType createTestCaseType() {
        return new TestCaseType();
    }

}
