//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-3273 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.05.12 at 11:47:00 AM PDT 
//


package com.sun.japex.testsuite;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TestCaseGroupType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TestCaseGroupType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.sun.com/japex/testSuite}ParamOrParamGroup" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;group ref="{http://www.sun.com/japex/testSuite}TestCaseOrTestCaseGroup" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TestCaseGroupType", propOrder = {
    "paramOrParamGroup",
    "testCaseOrTestCaseGroup"
})
public class TestCaseGroupType {

    @XmlElements({
        @XmlElement(name = "paramGroup", namespace = "http://www.sun.com/japex/testSuite", required = true, type = ParamOrParamGroupType.class),
        @XmlElement(name = "param", namespace = "http://www.sun.com/japex/testSuite", required = true, type = ParamType.class)
    })
    protected List<Object> paramOrParamGroup;
    @XmlElements({
        @XmlElement(name = "testCaseGroup", namespace = "http://www.sun.com/japex/testSuite", required = true, type = TestCaseGroupType.class),
        @XmlElement(name = "testCase", namespace = "http://www.sun.com/japex/testSuite", required = true, type = TestCaseType.class)
    })
    protected List<Object> testCaseOrTestCaseGroup;
    @XmlAttribute(required = true)
    protected String name;

    /**
     * Gets the value of the paramOrParamGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paramOrParamGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParamOrParamGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParamOrParamGroupType }
     * {@link ParamType }
     * 
     * 
     */
    public List<Object> getParamOrParamGroup() {
        if (paramOrParamGroup == null) {
            paramOrParamGroup = new ArrayList<Object>();
        }
        return this.paramOrParamGroup;
    }

    /**
     * Gets the value of the testCaseOrTestCaseGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the testCaseOrTestCaseGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTestCaseOrTestCaseGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TestCaseGroupType }
     * {@link TestCaseType }
     * 
     * 
     */
    public List<Object> getTestCaseOrTestCaseGroup() {
        if (testCaseOrTestCaseGroup == null) {
            testCaseOrTestCaseGroup = new ArrayList<Object>();
        }
        return this.testCaseOrTestCaseGroup;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
